### ISSUE TITLE
it doesn't work

### ISSUE THREAD

**Issue by tank-trax** [keenanpepper/musescore-xentuner#1]
I am on Linux using Musescore 3 and this does not work as advertised

I have Xenhamronic Tuner enabled
I apply 19edo 
Add notes add sharps, flats, double sharps, double flats, it's still 12 edo

for example  C sharp = D flat, C double sharp = D

what is going wrong here?

**Comment by keenanpepper** [comment]
I will look at this soon.

**Comment by tank-trax** [comment]
I got it working in version 3.6.2
